# Generated by Django 3.2.25 on 2025-03-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_breed_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(blank=True, help_text='введите породу собаки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='catalog.breed', verbose_name='порода'),
        ),
    ]
